name: Docker CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - "/Lab1/Base"
  workflow_dispatch: # to allow run action via github interface

jobs:

  build: # job name

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "/Lab1/Base"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push to Docker hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: pashabezk/ITMO_clouds:${{ github.run_number }}
