name: Docker CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - "Lab3/Base/**"
      - ".github/workflows/**"
  workflow_dispatch: # to allow run action via github interface

jobs:

  build: # job name

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "/Lab3/Base"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push to Docker hub
        uses: docker/build-push-action@v2
        with:
          context: ./Lab3/Base/
          push: true
          tags: pashabezk/itmo_clouds:${{ github.run_number }} , pashabezk/itmo_clouds:latest
